# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j7xelte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j7xelte/proprietary/vendor/bin/hw/android.hardware.bluetooth@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.bluetooth@1.0-service \
    vendor/samsung/j7xelte/proprietary/vendor/bin/hw/android.hardware.sensors@1.0-service:$(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.sensors@1.0-service \
    vendor/samsung/j7xelte/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/vendor/etc/init/android.hardware.bluetooth@1.0-service.rc \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/bcmdhd_apsta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/bcmdhd_apsta.bin_3s:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_apsta.bin_3s \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin_3s:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_mfg.bin_3s \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/bcmdhd_sta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/bcmdhd_sta.bin_3s:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bcmdhd_sta.bin_3s \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/cred.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/cred.conf \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/nvram.txt:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram.txt \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/nvram.txt_3s:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/nvram.txt_3s \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/samsung/j7xelte/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/bcm4343A0_V0079.0280.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm4343A0_V0079.0280.hcd \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/bcm43438_V0075.0303.hcd:$(TARGET_COPY_OUT_VENDOR)/firmware/bcm43438_V0075.0303.hcd \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/fimc_is_lib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_lib.bin \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/sec_s3nrn80_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_s3nrn80_firmware.bin \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/setfile_3l2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_3l2.bin \
    vendor/samsung/j7xelte/proprietary/vendor/firmware/setfile_5e3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_5e3.bin \
    vendor/samsung/j7xelte/proprietary/vendor/lib/hw/android.hardware.bluetooth@1.0-impl.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/android.hardware.bluetooth@1.0-impl.so \
    vendor/samsung/j7xelte/proprietary/vendor/lib/hw/sensors.universal7870.so:$(TARGET_COPY_OUT_VENDOR)/lib/hw/sensors.universal7870.so \
    vendor/samsung/j7xelte/proprietary/vendor/lib/libbt-vendor.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbt-vendor.so \
    vendor/samsung/j7xelte/proprietary/vendor/lib/vendor.samsung.hardware.nfc@1.0.so:$(TARGET_COPY_OUT_VENDOR)/lib/vendor.samsung.hardware.nfc@1.0.so
